/**
*
*Copyright 2010 OuterCurve Foundation
*
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at
*
*http://www.apache.org/licenses/LICENSE-2.0
*
*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
*/
/**
* This code was generated by the tool 'odatagen'.
* Runtime Version:1.0
*
* Changes to this file may cause incorrect behavior and will be lost if
* the code is regenerated.
*/
/**
* Defines default Data Service URL for this proxy class
*/
#define DEFAULT_SERVICE_URL @""


#define DataServiceVersion @"1.0"

#import "ODataObject.h"
#import "ObjectContext.h"
#import "DataServiceQuery.h"
#import "ODataGUID.h"
#import "ODataBool.h"
#import  "mProperties.h"


/**
 * @interface:Box
 * @Type:EntityType
 
 * @key:BoxID* 
 */
@interface DoveSiButtaModel_Box : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_BoxID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:50
	* @FixedLength:false
	*/
	NSString *m_Title;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_EventDate;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:256
	* @FixedLength:false
	*/
	NSString *m_Description;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:256
	* @FixedLength:false
	*/
	NSString *m_HostedById;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:256
	* @FixedLength:false
	*/
	NSString *m_HostedBy;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:20
	* @FixedLength:false
	*/
	NSString *m_ContactPhone;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:50
	* @FixedLength:false
	*/
	NSString *m_Address;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:30
	* @FixedLength:false
	*/
	NSString *m_Country;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_Latitude;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_Longitude;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:50
	* @FixedLength:false
	*/
	NSString *m_BoxType;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:50
	* @FixedLength:false
	*/
	NSString *m_Picture_Filename;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Binary
	*/
	NSData *m_Picture_File;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Ratings_Boxes
	* @FromRole:Boxes
	* @ToRole:Ratings
	*/
	NSMutableArray *m_Ratings;
	
}

@property ( nonatomic , retain , getter=getBoxID , setter=setBoxID )NSNumber *m_BoxID;
@property ( nonatomic , retain , getter=getTitle , setter=setTitle ) NSString *m_Title;
@property ( nonatomic , retain , getter=getEventDate , setter=setEventDate )NSDate *m_EventDate;
@property ( nonatomic , retain , getter=getDescription , setter=setDescription ) NSString *m_Description;
@property ( nonatomic , retain , getter=getHostedById , setter=setHostedById ) NSString *m_HostedById;
@property ( nonatomic , retain , getter=getHostedBy , setter=setHostedBy ) NSString *m_HostedBy;
@property ( nonatomic , retain , getter=getContactPhone , setter=setContactPhone ) NSString *m_ContactPhone;
@property ( nonatomic , retain , getter=getAddress , setter=setAddress ) NSString *m_Address;
@property ( nonatomic , retain , getter=getCountry , setter=setCountry ) NSString *m_Country;
@property ( nonatomic , retain , getter=getLatitude , setter=setLatitude )NSDecimalNumber *m_Latitude;
@property ( nonatomic , retain , getter=getLongitude , setter=setLongitude )NSDecimalNumber *m_Longitude;
@property ( nonatomic , retain , getter=getBoxType , setter=setBoxType ) NSString *m_BoxType;
@property ( nonatomic , retain , getter=getPicture_Filename , setter=setPicture_Filename ) NSString *m_Picture_Filename;
@property ( nonatomic , retain , getter=getPicture_File , setter=setPicture_File )NSData *m_Picture_File;
@property ( nonatomic , retain , getter=getRatings , setter=setRatings )NSMutableArray *m_Ratings;

+ (id) CreateBoxWithboxid:(NSNumber *)aBoxID title:(NSString *)aTitle eventdate:(NSDate *)aEventDate description:(NSString *)aDescription hostedby:(NSString *)aHostedBy contactphone:(NSString *)aContactPhone address:(NSString *)aAddress country:(NSString *)aCountry latitude:(NSDecimalNumber *)aLatitude longitude:(NSDecimalNumber *)aLongitude boxtype:(NSString *)aBoxType;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Rating
 * @Type:EntityType
 
 * @key:RatingID* 
 */
@interface DoveSiButtaModel_Rating : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_RatingID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_BoxID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:256
	* @FixedLength:false
	*/
	NSString *m_AttendeeName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:256
	* @FixedLength:false
	*/
	NSString *m_AttendeeNameId;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_RatingValue;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Ratings_Boxes
	* @FromRole:Ratings
	* @ToRole:Boxes
	*/
	NSMutableArray *m_Box;
	
}

@property ( nonatomic , retain , getter=getRatingID , setter=setRatingID )NSNumber *m_RatingID;
@property ( nonatomic , retain , getter=getBoxID , setter=setBoxID )NSNumber *m_BoxID;
@property ( nonatomic , retain , getter=getAttendeeName , setter=setAttendeeName ) NSString *m_AttendeeName;
@property ( nonatomic , retain , getter=getAttendeeNameId , setter=setAttendeeNameId ) NSString *m_AttendeeNameId;
@property ( nonatomic , retain , getter=getRatingValue , setter=setRatingValue )NSNumber *m_RatingValue;
@property ( nonatomic , retain , getter=getBox , setter=setBox )NSMutableArray *m_Box;

+ (id) CreateRatingWithratingid:(NSNumber *)aRatingID boxid:(NSNumber *)aBoxID attendeename:(NSString *)aAttendeeName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * Container interface DoveSiButtaEntities, Namespace: DoveSiButtaModel
 */
@interface DoveSiButtaEntities : ObjectContext
{
	 NSString *m_OData_etag;
	 DataServiceQuery *m_Boxes;
	 DataServiceQuery *m_Ratings;
	
}

@property ( nonatomic , retain , getter=getEtag , setter=setEtag )NSString *m_OData_etag;
@property ( nonatomic , retain , getter=getBoxes , setter=setBoxes ) DataServiceQuery *m_Boxes;
@property ( nonatomic , retain , getter=getRatings , setter=setRatings ) DataServiceQuery *m_Ratings;

- (id) init;
- (id) initWithUri:(NSString*)anUri credential:(id)acredential;
- (NSArray *) FindUpcomingItems;
- (NSArray *) FindAllItems;
- (NSArray *) ItemsNearMeWithplaceorzip:(NSString *)placeOrZip;
- (NSArray *) ItemsNearMeByCoordinatesWithlatitude:(NSDecimalNumber *)latitude longitude:(NSDecimalNumber *)longitude;
- (NSString *) CreateNewItemWithtitle:(NSString *)title latitude:(NSDecimalNumber *)latitude longitude:(NSDecimalNumber *)longitude address:(NSString *)address boxtype:(NSString *)boxType picture_filename:(NSString *)picture_filename;
- (NSString *) SetFileWithitemid:(NSNumber *)itemID file:(NSData *)file;
- (NSString *) SetFileBase64Withitemid:(NSNumber *)itemID filebase64:(NSString *)fileBase64;
- (NSString *) GetFileWithitemid:(NSNumber *)itemID;
- (NSString *) LoginWithusername:(NSString *)username password:(NSString *)password;
- (id) boxes;
- (id) ratings;
- (void) addToBoxes:(id)anObject;
- (void) addToRatings:(id)anObject;

@end
